// The grammar pattern library. To add a structure: add an entry here, then run
// `npm run gen` to build its exercise bank. hanzi tokens are "char|pinyin".

export const CATS = [
  ["identity", "Identity & description"],
  ["question", "Questions"],
  ["location", "Existence & location"],
  ["action", "Actions & time"],
  ["degree", "Degree & comparison"],
  ["quantity", "Quantity & negation"],
  ["extra", "More HSK 1 staples"],
];
export const CAT_LABEL = Object.fromEntries(CATS.map(([k, l]) => [k, l]));

export const STRUCTURES = [
  { id: "shi", cat: "identity", name: "是 — identity (A = B)", pattern: "A 是|shì B",
    rule: "是 links two things that are equal: identity, role, nationality. Drop 是 before adjectives — use 很 instead.",
    zh: "我|wǒ 是|shì 学|xué 生|shēng", en: "I am a student." },
  { id: "de", cat: "identity", name: "的 — possessive (A 的 N)", pattern: "A 的|de N",
    rule: "的 marks possession or modification: 我的手机 = my phone. Often dropped for close relations: 我妈妈.",
    zh: "这|zhè 是|shì 我|wǒ 的|de 手|shǒu 机|jī", en: "This is my phone." },
  { id: "adj", cat: "identity", name: "Adjective predicate (A 很 adj)", pattern: "A 很|hěn adj",
    rule: "Chinese adjectives don't take 是. Use 很 as a neutral link: 今天很热. Bare 今天热 sounds like a comparison.",
    zh: "今|jīn 天|tiān 很|hěn 热|rè", en: "It's hot today." },
  { id: "xihuan", cat: "identity", name: "喜欢 — like (A 喜欢 X)", pattern: "A 喜欢|xǐhuan X",
    rule: "喜欢 takes a noun OR a verb phrase: 我喜欢咖啡 / 我喜欢喝咖啡.",
    zh: "我|wǒ 喜|xǐ 欢|huan 喝|hē 咖|kā 啡|fēi", en: "I like drinking coffee." },

  { id: "ma", cat: "question", name: "吗 — yes/no question", pattern: "S 吗|ma ？",
    rule: "Add 吗 to the end of a statement for a yes/no question — no word-order change.",
    zh: "你|nǐ 是|shì 学|xué 生|shēng 吗|ma", en: "Are you a student?" },
  { id: "wh", cat: "question", name: "WH-question (swap in place)", pattern: "… 什么|shénme / 谁|shéi / 哪里|nǎlǐ ？",
    rule: "Keep the statement's word order and swap the unknown for a question word — nothing fronts like in English.",
    zh: "你|nǐ 是|shì 哪|nǎ 里|lǐ 人|rén", en: "Where are you from?" },
  { id: "ne", cat: "question", name: "呢 — and you? (N 呢?)", pattern: "N 呢|ne ？",
    rule: "呢 bounces a just-asked question back: 我很好，你呢？ Also softens 'where is…': 我的手机呢？",
    zh: "我|wǒ 很|hěn 好|hǎo 你|nǐ 呢|ne", en: "I'm good, and you?" },
  { id: "zmy", cat: "question", name: "怎么样 — how is it?", pattern: "N 怎么样|zěnmeyàng ？",
    rule: "Asks for a state or opinion: 今天天气怎么样？ Answer with 很 / 挺…的 / 太…了.",
    zh: "今|jīn 天|tiān 天|tiān 气|qì 怎|zěn 么|me 样|yàng", en: "How's the weather today?" },
  { id: "jiduoshao", cat: "question", name: "几 / 多少 — how many", pattern: "几|jǐ + mw + N  /  多少|duōshao + N",
    rule: "几 for small countable amounts, and it needs a measure word: 几个人. 多少 for larger or open counts, mw optional: 多少钱.",
    zh: "你|nǐ 家|jiā 有|yǒu 几|jǐ 口|kǒu 人|rén", en: "How many people are in your family?" },

  { id: "zai-place", cat: "location", name: "在 — be at (A 在 place)", pattern: "A 在|zài place",
    rule: "在 + place = located somewhere: 我在家. Negate with 不在.",
    zh: "我|wǒ 在|zài 家|jiā", en: "I'm at home." },
  { id: "you-exist", cat: "location", name: "有 — there is (place 有 thing)", pattern: "place 方位词 有|yǒu thing",
    rule: "有 states existence at a location: 桌子上有电脑. Negate with 没有.",
    zh: "桌|zhuō 子|zi 上|shàng 有|yǒu 电|diàn 脑|nǎo", en: "There's a computer on the desk." },
  { id: "fangwei", cat: "location", name: "方位词 — location words", pattern: "A 在|zài place 上面|shàngmiàn / 里面|lǐmiàn",
    rule: "Position words follow the place noun: 猫在桌子下面. Common set: 上/下/里/外/前/后/左边/右边/旁边/对面/中间.",
    zh: "猫|māo 在|zài 桌|zhuō 子|zi 下|xià 面|miàn", en: "The cat is under the table." },
  { id: "you-have", cat: "location", name: "有 — have (A 有 N)", pattern: "A 有|yǒu N",
    rule: "Possession. Negate ONLY with 没有, never 不有.",
    zh: "我|wǒ 有|yǒu 一|yí 个|gè 手|shǒu 机|jī", en: "I have a phone." },

  { id: "zai-prog", cat: "action", name: "在 — in progress (A 在 V)", pattern: "A 在|zài V",
    rule: "在 before a verb = happening now: 我在看电视 (often closed with 呢). Don't confuse with 在 + place.",
    zh: "我|wǒ 在|zài 看|kàn 电|diàn 视|shì", en: "I'm watching TV." },
  { id: "time-place", cat: "action", name: "Time placement (S + time + V)", pattern: "S time V （O）",
    rule: "Time-when goes BEFORE the verb, never after: 我十一点吃午饭, not …吃午饭十一点. Can also lead the sentence.",
    zh: "我|wǒ 十|shí 一|yī 点|diǎn 吃|chī 午|wǔ 饭|fàn", en: "I have lunch at 11." },
  { id: "gen", cat: "action", name: "跟 / 和 — with (S 跟 sb V)", pattern: "S 跟|gēn sb place V O",
    rule: "跟/和 + person = doing it together. Order: subject + with-whom + place + verb.",
    zh: "我|wǒ 跟|gēn 妈|mā 妈|ma 去|qù 超|chāo 市|shì", en: "I go to the supermarket with my mum." },
  { id: "transport", cat: "action", name: "坐/开/骑 — by transport", pattern: "S 坐|zuò / 开|kāi / 骑|qí vehicle 去|qù place",
    rule: "Means of transport comes before 去 + place: 我坐飞机去中国. 坐 = ride in, 开 = drive, 骑 = ride astride, 走路 = walk.",
    zh: "我|wǒ 坐|zuò 飞|fēi 机|jī 去|qù 中|zhōng 国|guó", en: "I go to China by plane." },
  { id: "cong", cat: "action", name: "从 — from (从 A V)", pattern: "S 从|cóng A V",
    rule: "从 marks a starting point: 我从北京回来.",
    zh: "我|wǒ 从|cóng 北|běi 京|jīng 回|huí 来|lái", en: "I'm coming back from Beijing." },
  { id: "dasuan", cat: "action", name: "打算 — plan to (S 打算 V)", pattern: "S 打算|dǎsuan V",
    rule: "打算 = intend / plan to do.",
    zh: "我|wǒ 打|dǎ 算|suan 住|zhù 在|zài 宾|bīn 馆|guǎn", en: "I plan to stay at a hotel." },
  { id: "hui", cat: "action", name: "会 — will (time后 S 会 V)", pattern: "time 后|hòu S 会|huì V",
    rule: "会 marks a future intention or likelihood. time + 后 = 'after / in that much time'.",
    zh: "一|yí 个|gè 月|yuè 后|hòu 我|wǒ 会|huì 去|qù 北|běi 京|jīng", en: "In a month I'll go to Beijing." },
  { id: "le", cat: "action", name: "了 — completed / changed", pattern: "S V 了|le （O）",
    rule: "了 marks a completed action (我吃了) or a new situation (我二十二岁了 = I've turned 22).",
    zh: "我|wǒ 吃|chī 了|le", en: "I've eaten." },
  { id: "haimei", cat: "action", name: "还没 — not yet", pattern: "还没|háiméi V",
    rule: "Negates a 了 question: 你吃了吗？— 还没. Completion is negated by 没, not 不.",
    zh: "还|hái 没|méi 吃|chī", en: "Not eaten yet." },

  { id: "tai", cat: "degree", name: "太 + adj + 了 — too…", pattern: "太|tài adj 了|le",
    rule: "Strong, often excessive degree.",
    zh: "今|jīn 天|tiān 太|tài 热|rè 了|le", en: "It's too hot today." },
  { id: "ting", cat: "degree", name: "挺 + adj + 的 — quite…", pattern: "挺|tǐng adj 的|de",
    rule: "Mild positive degree: 挺好的. Contrast 不太 + adj = 'not very' (不太好).",
    zh: "我|wǒ 挺|tǐng 好|hǎo 的|de", en: "I'm pretty good." },
  { id: "hao-v", cat: "degree", name: "好 + verb (好玩/好吃/好听)", pattern: "N 很|hěn 好|hǎo V",
    rule: "好 + a sense verb = 'nice to…': 好吃 tasty, 好喝 nice to drink, 好玩 fun, 好听 nice to hear, 好看 good-looking.",
    zh: "网|wǎng 球|qiú 很|hěn 好|hǎo 玩|wán", en: "Tennis is fun." },
  { id: "bi", cat: "degree", name: "比 — comparison (A 比 B adj)", pattern: "A 比|bǐ B adj",
    rule: "A 比 B + adj = A is more adj than B. Never put 很 before the adjective in a 比 sentence.",
    zh: "今|jīn 天|tiān 比|bǐ 昨|zuó 天|tiān 热|rè", en: "Today is hotter than yesterday." },
  { id: "li", cat: "degree", name: "离 — distance (A 离 B 远/近)", pattern: "A 离|lí B 远|yuǎn / 近|jìn",
    rule: "离 measures how far/near A is from B. A = the thing located, B = the reference point.",
    zh: "我|wǒ 家|jiā 离|lí 学|xué 校|xiào 很|hěn 近|jìn", en: "My home is close to school." },

  { id: "mw", cat: "quantity", name: "Measure words (num + mw + N)", pattern: "num mw N",
    rule: "A measure word sits between number and noun. 个 is the default; specific ones exist: 口 (family), 只 (animals), 杯 (cups), 条 (long things).",
    zh: "我|wǒ 有|yǒu 三|sān 个|gè 朋|péng 友|you", en: "I have three friends." },
  { id: "liang", cat: "quantity", name: "二 vs 两 — saying 'two'", pattern: "两|liǎng mw N",
    rule: "Use 两 before a measure word (两个人), but 二 for counting, numbers and ordinals (二, 第二, 二楼).",
    zh: "我|wǒ 有|yǒu 两|liǎng 个|gè 苹|píng 果|guǒ", en: "I have two apples." },
  { id: "duo", cat: "quantity", name: "多 — more than (num + 多)", pattern: "num 多|duō mw N",
    rule: "多 after a round number = 'X-something'. Position shifts: 一个多月 vs 二十多个人.",
    zh: "我|wǒ 们|men 学|xué 院|yuàn 有|yǒu 一|yì 千|qiān 多|duō 个|gè 人|rén", en: "Our college has over a thousand people." },
  { id: "bu-mei", cat: "quantity", name: "不 vs 没 — two negatives", pattern: "不|bù V/adj   /   没|méi 有/V了",
    rule: "不 negates habits, preferences, futures, adjectives: 我不喜欢. 没 negates 有 and completed actions: 我没有 / 我没吃.",
    zh: "我|wǒ 没|méi 有|yǒu 手|shǒu 机|jī", en: "I don't have a phone." },

  { id: "ye", cat: "extra", name: "也 — also (S 也 V)", pattern: "S 也|yě V/adj",
    rule: "也 = also/too, placed before the verb/adjective: 我也是学生. Never at the end like English 'too'.",
    zh: "我|wǒ 也|yě 是|shì 学|xué 生|shēng", en: "I'm also a student." },
  { id: "dou", cat: "extra", name: "都 — all/both (S 都 V)", pattern: "S 都|dōu V/adj",
    rule: "都 sums up a plural subject and sits before the verb: 我们都是学生.",
    zh: "我|wǒ 们|men 都|dōu 是|shì 学|xué 生|shēng", en: "We're all students." },
  { id: "zhi", cat: "extra", name: "只 / 只有 — only", pattern: "S 只|zhǐ V  /  S 只有|zhǐyǒu N",
    rule: "只 before a verb limits the action / amount: 我只有一个手机.",
    zh: "我|wǒ 只|zhǐ 有|yǒu 一|yí 个|gè 手|shǒu 机|jī", en: "I only have one phone." },
  { id: "xuyao", cat: "extra", name: "需要 — need (sb 需要 sth)", pattern: "S 需要|xūyào N/V",
    rule: "需要 = need; takes a noun or a verb.",
    zh: "我|wǒ 需|xū 要|yào 一|yì 杯|bēi 水|shuǐ", en: "I need a glass of water." },
  { id: "yinwei", cat: "extra", name: "为什么 — why / 因为 — because", pattern: "为什么|wèishénme … — 因为|yīnwèi …",
    rule: "为什么 asks why; 因为 answers with a reason.",
    zh: "因|yīn 为|wèi 米|mǐ 饭|fàn 很|hěn 好|hǎo 吃|chī", en: "Because rice is delicious." },
  { id: "yiwei", cat: "extra", name: "以为 — mistakenly thought", pattern: "S 以为|yǐwéi …",
    rule: "以为 = thought (wrongly): 我以为你在家 — but you weren't. Use 觉得/想 for a neutral 'think'.",
    zh: "我|wǒ 以|yǐ 为|wéi 你|nǐ 在|zài 家|jiā", en: "I thought you were home." },
];
